name: Oliver Roick
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:title.html
excerpt_separator: "====="
source: src
collections:
  work:
    output: false
plugins:
  - jekyll-sitemap
  - ./_plugins/post_update
defaults:
  - scope:
      path: "files/**/*"
    values:
      sitemap: false
  - scope:
      path: "404.html"
    values:
      sitemap: false
