[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

[[plugins]]
  package = "netlify-plugin-minify-html"

  [plugins.inputs.minifierOptions]
    removeComments = true
    collapseInlineTagWhitespace = false

[[plugins]]
  package = "netlify-plugin-html-validate"

  [plugins.inputs]
    ext = "html"
    config = ".htmlvalidate.json"
