[build]
  command = "make build"

[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

[[plugins]]
  package = "netlify-plugin-minify-html"

  [plugins.inputs.minifierOptions]
    removeComments = true
    collapseInlineTagWhitespace = false

[[plugins]]
  package = "netlify-plugin-html-validate"

  [plugins.inputs]
    ext = "html"
    config = ".htmlvalidate.json"

[[redirects]]
  from = "/wheredoyougo"
  to = "https://oliverroick.github.io/wheredoyougo/"
  status = 301

[[redirects]]
  from = "/django-skivvy"
  to = "https://oliverroick.github.io/django-skivvy/"
  status = 301

[[redirects]]
  from = "https://oliverroick.de/*"
  to = "https://oliverroick.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/thoughts/*"
  to = "/writing/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/code/*"
  to = "/writing/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/conferences/*"
  to = "/writing/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/talks/*"
  to = "/writing/:splat"
  status = 301
  force = true
