[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

[[plugins]]
  package = "netlify-plugin-minify-html"

  [plugins.inputs.minifierOptions]
    removeComments = true
    collapseInlineTagWhitespace = false

[[redirects]]
  from = "/wheredoyougo"
  to = "https://oliverroick.github.io/wheredoyougo/"
  status = 301

[[redirects]]
  from = "/django-skivvy"
  to = "https://oliverroick.github.io/django-skivvy/"
  status = 301
