name: notfoundbot
on: ['push']

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fix links
        uses: oliverroick/notfoundbot@custom-directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
