name: notfoundbot
on:
  schedule:
    - cron: "0 7 * * 1"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fix links
        uses: oliverroick/notfoundbot@custom-directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONTENT_DIR: src/_posts
